# **Linguagem Python**
---
*   Lançado por Guido Van Rossum em 1991.
*   Uma das linguagens mais utilizadas no mundo.
*   Linguagem simples e prática.
*   Fonte livre e aberta.
*   Grande comunidade colaborativa.
*   O Python é suportado pelo Windowns, Linux, Macintosh, Solaris...
*   Alto nível para várias aplicações: Desenvolvimento Web, Ciência de Dados, Inteligência Artificial e Computação Gráfica.
---
**Temos vários ambiente de desenvolvimento integrado (IDE)**
*   PyCharm
*   Spyder
*   Geany
*   PyDev
*   Pyzo
*   Komodo Edit
*   Atom ide
*   Visual Studio Code
---
**Ambiente de desenvolvimento interativo baseado na Web**
*   Jupyter Notebook
*   Jupyter Lab
    - Arquivos no desktop;
    - Dependente da capacidade de processamento do computador.
    - Necessita instalação.
*   Google Colaboratory (Google Colab)
    - Executa código dos servidores em nuvem do Google.
    - Não necessita de instalação.
    - Aproveitamento da potência de hardware do Google(GPUs e TPUs), independentemente da potência da sua máquina.
      - CPU (Unidade de Processamento Central): Processador computacional de propósito geral.
      - GPU (Unidade de Processamento Gráfico): Acelera a renderização gráfica.
      - TPU (Unidade de Processamento Tensorial): Acelera tarefas de aprendizagem profunda.
---
**Anaconda(Python)**
*   Plataforma de distribuição para ciência de dados com Python.
*   Simplifica o gerenciamento e implantação de pacotes.
*   Pacotes esse como:
    - Jupyter, Scipy, Spyder, NumPy, Dask, Bokeh, Scikit Learn, TensorFlow, Numba, Panel, Pandas, Pytorch, Conda, Matplotlib, HoloViews
---
*   Numpy (Computação matemática com Python)
*   Pandas (Manipulação e análise de dados. Trabalha em conjunto com o Numpy.
*   Scikit Learn (Aprendizado de máquina (Machine Learning) em Python.
*   Statsmodels (Modelagem e testes Estatísticos.
**Bibliotecas gráficas**
*   matplotlib (Criação de gráficos e visualizações de dados em geral.
*   seaborn (Visualização de dados baseado no Matplotlib. Fornece interface de alto nível para desenhar gráficos estatpisticos atraentes e informativos.)
*   plotly (Criação de gráficos e visualização de dados de forma interativa, com interface de alto nível)
**Temos mais bibliotecas**
*   Scipy é uma biblioteca baseado em Python, de código aberto, para matemática, ciências e engenharia.
*   TensorFlow (Biblioteca de código aberto. Desenvolvido pela Google Brain Team para aprendizado de máquina e pesquisa de redes neurais profundas.
*   Keras (Biblioteca de rede neural de código aberto. Roda em cima de TensorFlow. Permite experimentação rápida com redes neurais profundas e possui facilidade de uso.)
---






















# **Introdução**

Vamos apreender um pouco dos comandos básicos de Python para aplicar em redes neurais.

In [1]:
print('Olá Mundo!')

Olá Mundo!


In [2]:
mensagem = 'Olá Mundo'

In [3]:
print(mensagem)

Olá Mundo


In [4]:
mensagem

'Olá Mundo'

In [6]:
nome = input('Qual é o seu nome? ')

Qual é o seu nome? Jessica


In [7]:
print('Meu nome é: ',nome)

Meu nome é:  Jessica


In [8]:
nome = input('Qual é o seu nome? ')
print('Meu nome é: ',nome)

Qual é o seu nome? Jessica
Meu nome é:  Jessica


# **operadores Matemáticos**

In [9]:
n1= 3

In [10]:
n2 = 5

In [11]:
soma = n1 + n2
print(soma)

8


In [12]:
soma = soma + n2
soma

13

In [13]:
soma += n2
soma

18

In [14]:
substracao = n1 - n2
substracao

-2

In [16]:
multiplicacao = n1+ n2
multiplicacao

8

In [19]:
potenciacao = n1**n2
potenciacao

243

In [20]:
# usando função para fazer a potenciação
potenciacao2 = pow(n1,n2)
potenciacao2

243

In [21]:
divisao = n2/n1
divisao

1.6666666666666667

In [23]:
# aqui se pega o resultado inteiro da divisão
div = n2 // n1
div

1

In [22]:
resto = n2%n1
resto

2

# **Importações de bibliotecas, pacotes e módulos**

In [25]:
# biblioteca matemática
import math

In [34]:
n = 38

In [35]:
raiz = math.sqrt(n)
print('A raiz de {} é igual a {:.2f}'.format(n, raiz))

A raiz de 38 é igual a 6.16


In [37]:
raiz

6.164414002968976

In [38]:
# sem usar a função de raiz quadrado
raiz2 = n ** 0.5
raiz2

6.164414002968976

In [41]:
print('{:.2f}'.format(raiz2))

6.16


In [43]:
# As vezes não é legal trazer todas as funções de uma biblioteca, então melhor dizer qual você deseja trazer.
from math import sqrt
raiz3 = sqrt(n)
raiz3

6.164414002968976

In [44]:
from math import factorial, sqrt

In [45]:
fatorial = factorial(4) 
# fatorial: 4! = 4.3.2 = 24
fatorial

24

In [47]:
fatorial_raiz = factorial(sqrt(16))
fatorial_raiz

24

In [53]:
import random
num = random.randint(1, 10)
num

2

In [55]:
from random import random, randint

In [56]:
random?

In [57]:
randint?

In [58]:
num2 = random()
num2

0.14896620154575457

In [63]:
num2 = randint(1, 100)
num2

19

# **Estrutura condicional**

In [64]:
nota = 6

In [65]:
if nota >= 7:
  print('Aprovado!')
else:
  print('Reprovado!')

Reprovado!


In [66]:
if nota >= 7:
  print('Aprovado!')
elif nota >= 6 and nota < 7:
  print('Recuperação!')
else:
  print('Reprovado!')

Recuperação!


# **Estrutura de Repetição**

In [67]:
for valor in range(0,4):
  print(valor)

0
1
2
3


In [68]:
lista = [1,2,3,4,5,10]
for numero in lista:
  print(numero)

1
2
3
4
5
10


In [69]:
lista = [1,2,3,4,5,10]
for numero in lista:
  print(numero * 2)

2
4
6
8
10
20


In [74]:
soma = 0
cont = 0
for valor in range(1,6):
  num = int(input('Digite o {} valor: '.format(valor)))
  if num % 2 == 0:
    soma = soma + num
    cont = cont + 1
print('Você informou {} números pares e a soma deles é igual a {}'.format(cont, soma))

Digite o 1 valor: 5
Digite o 2 valor: 6
Digite o 3 valor: 12
Digite o 4 valor: 3
Digite o 5 valor: 9
Você informou 2 números pares e a soma deles é igual a 18


In [75]:
cont = 1
while cont < 10:
  soma = cont + 10
  print(soma)
  cont+=1
print('Terminou!')

11
12
13
14
15
16
17
18
19
Terminou!


# **Listas, Tuplas e Dicionários**

***Listas***

In [84]:
num = [1,2,5,8,12]

In [85]:
num

[1, 2, 5, 8, 12]

In [86]:
num[3]

8

In [87]:
# Podemos colocar outro valor na posição 3 no lugar do 8
num[3] = 10
num

[1, 2, 5, 10, 12]

In [88]:
# aqui você adiciona a lista um valor
num.append(8)
num

[1, 2, 5, 10, 12, 8]

In [89]:
# colocar em ordem crescente
num.sort()
num

[1, 2, 5, 8, 10, 12]

In [90]:
# podemos adicionar um valor em uma posição
          #p,v
num.insert(2,0) # estamos colocando o valor 0 na posiçao 2
num

[1, 2, 0, 5, 8, 10, 12]

In [91]:
# podemos remover
num.remove(0)
num

[1, 2, 5, 8, 10, 12]

In [92]:
# podemos remover o valor de uma posição
num.pop(3)
num

[1, 2, 5, 10, 12]

***Tuplas***

In [93]:
num = (1,2,5,10,12)

In [95]:
# truplas é imutável, não podemos alterar ela igual fizemos na lista
# num[3] = 8

***Dicionários***

In [97]:
pessoas = {'nome': 'Jessica', 'sexo': 'femenino', 'idade': 30}
pessoas

{'nome': 'Jessica', 'sexo': 'femenino', 'idade': 30}

In [98]:
# adicionar novo elemento em nosso dicionário
pessoas['time'] = 'Bota Fogo'
pessoas

{'nome': 'Jessica', 'sexo': 'femenino', 'idade': 30, 'time': 'Bota Fogo'}

In [99]:
# remover
del pessoas['time']
pessoas

{'nome': 'Jessica', 'sexo': 'femenino', 'idade': 30}

# **Funções**

In [110]:
def pessoa(nome, idade):
  print('Olá', nome,'!','\n Sua idade é',idade, 'ano.s')

In [111]:
pessoa('Jessica', 30)

Olá Jessica ! 
 Sua idade é 30 ano.s


In [112]:
def maior(x,y):
  if x< y:
    print('O maior valor é', y)
  elif x == y:
    print('Os valores são iguais!')
  else:
    print('O maior valor é', x)

In [116]:
maior(25,50)

O maior valor é 50


In [117]:
def pitagoras(cat1, cat2, hip):
  if hip == '?':
    hip = (cat1**2+cat2**2)**(1/2)
    print('A hipotenusa é', hip)
  elif cat1 == '?':
    cat1 = (hip**2-cat2**2)**(1/2)
    print('O cateto é:', cat1)
  elif cat2 == '?':
    cat2 = (hip**2-cat1**2)**(1/2)
    print('O cateto é:', cat2)

In [120]:
pitagoras(4, 5, '?')

A hipotenusa é 6.4031242374328485


# **Função Lambda e map**

In [121]:
# Função Lambda é uma forma simplificada de escrever funções
def area_quadrado(x):
  area= x**2
  print(area)

In [122]:
area_quadrado(4)

16


In [123]:
area_quadrado2 = lambda x: x**2
area_quadrado2(4)

16

In [124]:
area_retangulo = lambda b, h: b*h
area_retangulo(2,4)

8

In [126]:
# map junta uma função junto com o valor que vai utilizar essa função
L = [2,4,5,7,10,6,12]
areas = list(map(lambda x : x**2, L))
print(areas)

[4, 16, 25, 49, 100, 36, 144]


# **List Comprehensions**

In [140]:
# Com List Comprehensions podemos otimizar a utilização de listas e diminui linhas de códigos.
Lista=[]
for valor in range(5):
  Lista.append(valor+10)
print(Lista)

[10, 11, 12, 13, 14]


In [141]:
lista = [valor+10 for valor in range(5)]
lista

[10, 11, 12, 13, 14]

In [143]:
lista = []
for n in range(1,30):
  if n % 4 == 0:
    lista.append(n)
print(lista)

[4, 8, 12, 16, 20, 24, 28]


In [145]:
multiplico = [n for n in range(1,30) if n % 4 == 0]
multiplico

[4, 8, 12, 16, 20, 24, 28]

In [146]:
conceito = ['azul' if nota >= 6 else 'vermelha' for nota in range(1,11)]
conceito

['vermelha',
 'vermelha',
 'vermelha',
 'vermelha',
 'vermelha',
 'azul',
 'azul',
 'azul',
 'azul',
 'azul']

# **Vetores (arrays) & Matrizes**

In [147]:
vetor = [1,2,4,6]

In [148]:
type(vetor)

list

In [149]:
matriz =[[1,2,3],
         [4,5,6],
         [7,8,9]]

In [150]:
type(matriz)

list

In [151]:
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [152]:
vetor

[1, 2, 4, 6]

In [153]:
import numpy as np

In [154]:
vetor2 = np.array([1, -3, 5.2, 7])

In [155]:
type(vetor2)

numpy.ndarray

In [156]:
vetor2

array([ 1. , -3. ,  5.2,  7. ])

In [157]:
matriz2 = np.ones((2,3))
matriz2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [158]:
type(matriz2)

numpy.ndarray

In [159]:
matriz3 = np.diag((2,4,6,8,10))
matriz3

array([[ 2,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  6,  0,  0],
       [ 0,  0,  0,  8,  0],
       [ 0,  0,  0,  0, 10]])

In [160]:
type(matriz3)

numpy.ndarray